version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: eazybank
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  accounts:
    build:
      context: ./Accounts
    image: prateekarya100/accounts:ms
#    container_name: accounts-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/eazybank
      SPRING_DATASOURCE_USERNAME: docker
      SPRING_DATASOURCE_PASSWORD: docker
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8081:8081"


  cards:
    build:
      context: ./Cards
    image: prateekarya100/cards:ms
#    container_name: cards-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/eazybank
      SPRING_DATASOURCE_USERNAME: docker
      SPRING_DATASOURCE_PASSWORD: docker
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "9000:8082"

  loans:
    build:
      context: ./Loans
    image: prateekarya100/loans:ms
#    container_name: loans-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/eazybank
      SPRING_DATASOURCE_USERNAME: docker
      SPRING_DATASOURCE_PASSWORD: docker
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8090:8083"


networks:
  default:
    name: mynetwork
    driver: bridge
