
spring:
  application:
    name: "gatewayserver"
  config:
    import:
      - "optional:configserver:http://localhost:8071"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
    info:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "EazyBank gateway server application"
    version: "1.0.0"

logging:
  level:
    com:
      gatewayserver: DEBUG


resilience4j:
  circuitbreaker:
    instances:
      accountsCircuitBreaker:
        slidingWindowSize: 5
        permitted-number-of-calls-in-half-open-state: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 4s

      cardsCircuitBreaker:
        slidingWindowSize: 50
        permitted-number-of-calls-in-half-open-state: 2
        failureRateThreshold: 5
        waitDurationInOpenState: 4s



