server:
  port: 8083

spring:
  application:
    name: "loans"
  profiles:
    active:
      - "prod"
  config:
    import:
      - "optional:configserver:http://localhost:8071"
  datasource:
    # url: jdbc:h2:mem:testdb
    # username: sa
    # password: ''
    # driverClassName: org.h2.Driver
    url: "jdbc:mysql://localhost:3307/loansdb"
#    url: "jdbc:mysql://localhost:3306/microservices"
    username: "root"
    password: "root"
    driver-class-name: "com.mysql.cj.jdbc.Driver"

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    # database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

info:
  app:
    name: "loans"
    description: "EazyBank loans application"
    version: "1.0.0"

logging:
  level:
    com:
      tomcat:
        Loans: DEBUG