server:
  port: 8083

spring:
  application:
    name: "loans"
  profiles:
    active:
      - "prod"
  config:
    import:
      - "optional:configserver:http://localhost:8071"
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
    driverClassName: org.h2.Driver
#    url: "jdbc:mysql://localhost:3309/loansdb"
#    url: "jdbc:mysql://localhost:3309/microservices"
#    username: "root"
#    password: "root"
#    driver-class-name: "com.mysql.cj.jdbc.Driver"

  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

info:
  app:
    name: "loans"
    description: "EazyBank loan application"
    version: "1.0.0"