#spring.application.name=eurekaserver

spring:
  application:
    name: "eurekaserver"
  config:
    import:
      - "optional:configserver:http://localhost:8071"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

eureka:
  instance:
#    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka/