server:
  port: 8083

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/microservices"
    username: "root"
    password: "root"
    driver-class-name: "com.mysql.cj.jdbc.Driver"

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

loans:
  message: "thank you for contacting loans microservices development team"
  contactDetails:
    developer: "prateek arya"
    email: "prateekarya100@gmail.com"
  onCallSupport:
    - 9650841442
    - 9123456789